name: Deploy Hexo site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: writname: Deploy Hexo site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Install dependencies and generate package-lock.json
        run: |
          npm install
          npm install hexo-cli -g
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add package-lock.json
          git commit -m "Add package-lock.json" || echo "No changes to commit"
          git push

      - name: Build with Hexo
        run: |
          hexo clean
          hexo generate

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: npm

      - name: Setup Pages
        uses: actions/configure-pages@v3
      
      - name: Generate package-lock.json
        run: |
          npm install
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add package-lock.json
          git commit -m "Add or update package-lock.json" || echo "No changes to commit"
          git push

      - name: Install dependencies
        run: npm ci

      - name: Build with Hexo
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
